### DISCUSSION TITLE
The background color of Toggle and Switch components is missing at 2.1.0

### DISCUSSION THREAD

**Discussion by aquarius-software** [TailGrids/tailgrids#5] [General]
I have upgraded the version of tailgrids package to 2.1.0.

Then I noticed the background color of Toggle and Switch components was missing.

I suppose this is because the CSS style below in tailwind.css has been removed at 2.1.0.

```css
input:checked ~ .dot {
    background: #3056D3;
    transform: translateX(100%);
}
``` 

 I would like to know the reason why the style has been removed.

Thanks in advance.
